spec:
  containers:
    - name: app-&{ depname }-ext
      image: /snowflake/images/snowflake_images/runtime-extensions:2025.4.3.16
      command:
        - /bin/sh
        - -c
        - "cp /libs/* /extensions; sleep inf"
      resources:
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          cpu: 100m
          memory: 1Gi
      volumeMounts:
        - name: extensions
          mountPath: /extensions
    - name: app-&{ depname }-srv
      image: /snowflake/images/snowflake_images/runtime-server:2025.4.3.16
      env:
        NIFI_WEB_HTTP_HOST: ''
        NIFI_WEB_HTTP_PORT: '8080'
        NIFI_WEB_HTTPS_HOST: ''
        NIFI_WEB_HTTPS_PORT: ''
        NIFI_SECURITY_KEYSTORE: ''
        NIFI_SECURITY_KEYSTORE_TYPE: ''
        NIFI_SECURITY_TRUSTSTORE: ''
        NIFI_SECURITY_TRUSTSTORE_TYPE: ''
        NIFI_REMOTE_INPUT_SECURE: 'false'
        NIFI_SECURITY_AUTORELOAD_ENABLED: 'false'
        NIFI_WEB_REQUEST_LOG_FORMAT: '%{client}a - %{Sf-Context-Current-User}i %t "%r" %s %O "%{Referer}i" "%{User-Agent}i"'
        NIFI_PROVENANCE_REPOSITORY_IMPLEMENTATION: 'org.apache.nifi.provenance.WriteAheadProvenanceRepository'
        NIFI_PROVENANCE_REPOSITORY_DIRECTORY_DEFAULT: '/resources/provenance_repository'
        NIFI_PROVENANCE_REPOSITORY_INDEXED_ATTRIBUTES: 'container.id,container.scope'
        NIFI_FLOWFILE_REPOSITORY_DIRECTORY: '/resources/flowfile_repository'
        NIFI_CONTENT_REPOSITORY_DIRECTORY_REPO1: '/content_repository'
        NIFI_CONTENT_REPOSITORY_ARCHIVE_MAX_RETENTION_PERIOD: '24 hours'
        NIFI_CONTENT_REPOSITORY_ARCHIVE_MAX_USAGE_PERCENTAGE: '80%'
        NIFI_FLOW_CONFIGURATION_FILE: '/resources/flow.json.gz'
        NIFI_DATABASE_DIRECTORY: '/resources/database_repository'
        NIFI_ASSET_MANAGER_PROPERTIES_DIRECTORY: '/resources/assets'
        NIFI_NAR_PERSISTENCE_PROVIDER_PROPERTIES_DIRECTORY: '/resources/nar_repository'
        NIFI_NAR_LIBRARY_DIRECTORY_EXTENSIONS: '/resources/nars'
      secrets:
        - snowflakeSecret: RUNTIME_SERVER_PROPERTIES_KEY
          envVarName: NIFI_SENSITIVE_PROPS_KEY
      readinessProbe:
        port: 8080
        path: /nifi-api/authentication/configuration
      resources:
        requests:
          cpu: 1500m
          memory: 3Gi
        limits:
          cpu: 2000m
          memory: 4Gi
      volumeMounts:
        - name: extensions
          mountPath: /opt/runtime/runtime-server/extensions
        - name: content-repository
          mountPath: /content_repository
        - name: resources
          mountPath: /resources
    - name: app-&{ depname }
      image: &{ accname }.registry.snowflakecomputing.com/&{ dbsname }/&{ depname }/images/app-&{ depname }:latest
      env:
        NGINX_PORT: 80
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 1Gi
      readinessProbe:
        port: 80
        path: /nifi-api/authentication/configuration
  endpoints:
    - name: runtime
      port: 8080
      public: false
      protocol: HTTP
    - name: gateway
      port: 80
      public: true
      protocol: HTTP
  volumes:
    - name: extensions
      source: block
      size: 4Gi
      uid: 1000
      gid: 1000
    - name: content-repository
      source: block
      size: 40Gi
      uid: 1000
      gid: 1000
    - name: resources
      source: block
      size: 50Gi
      uid: 1000
      gid: 1000
